### ISSUE TITLE
Allow collection to theme databases

### ISSUE THREAD

**Issue by ghost** [Rinnegatamante/CHMM#12]
A good idea would be to implement some sort of system where users could connect to a theme database and download themes over the net, stopping the need for themes to be copied over manually.

**Comment by ihaveamac** [comment]
this is already implemented, and it connects to 3dsthem.es. press R to switch to the theme downloader.

from the gbatemp thread: https://gbatemp.net/threads/release-chmm2-custom-home-menu-manager-2.397543/

> **Theme Downloader**
> 
> A = Execute selected option
> Y = Open theme preview
> R / Start = Swap to Base System
> Left / Right = Navigate through themes
> Up / Down = Navigate in Actions Menu
> SELECT = Change UI color
> Touch = Open Help Panel

**Comment by ghost** [comment]
TY, I really need to start updating my apps.
