### ISSUE TITLE
Music Stops Playing

### ISSUE THREAD

**Issue by Anonymous42456** [Rinnegatamante/CHMM#14]
After about the first loop, the music on my themes stops playing. Help?

**Comment by Rinnegatamante** [comment]
Are you using shuffle system? If so, musics can't be longer then 1:30.

**Comment by Anonymous42456** [comment]
I only have official themes from reddit.

**Comment by Anonymous42456** [comment]
All of the official Zelda themes to be exact.

**Comment by Rinnegatamante** [comment]
I've not asked you what themes are you using. I'm asking you if you're using shuffle system...

**Comment by Anonymous42456** [comment]
Yes

**Comment by Rinnegatamante** [comment]
musics can't be longer then 1:30. There also are more info on GBAtemp about this problem in official thread. You can ask to Ryumaru about possible fixes. This is not a CHMM2 flaw.

**Comment by Anonymous42456** [comment]
They are less than 1:30

**Comment by Rinnegatamante** [comment]
I suggest you to talk with Ryumaru in private cause he tested possible solutions about this issue. ( https://gbatemp.net/members/ryumaru.360795/ ). It's a common issue till CHMM2 v.2.0 and even if i tried several times to patch it, it looks like it's an issue in the shuffle system itself.

**Comment by Anonymous42456** [comment]
I can't. His profile is hidden.

**Comment by Anonymous42456** [comment]
Nvm I fixed it. I just reapplied all of the themes. Thanks for the help anyways.
