### ISSUE TITLE
Theme folder name seems to break installing and previewing themes

### ISSUE THREAD

**Issue by QuantumSoundings** [Rinnegatamante/CHMM#18]
I noticed whenever I had a folder with the name Pokémon chmm2 wouldn't be able to show a preview or install the theme. When I changed the title to Pokemon. Without the special e character it loaded up the preview and installed the theme perfectly.

**Comment by Rinnegatamante** [comment]
lpp-3ds doesn't support UTF8 encoding, only ASCII characters are allowed.

**Comment by QuantumSoundings** [comment]
Ok that makes a lot of sense then. Could you post that on the gbatemp page? I didn't see anything like that mentioned anywhere so that's why I posted this here. Of course I may have just not been looking hard enough.
