### ISSUE TITLE
Error installing theme

### ISSUE THREAD

**Issue by pascalharp** [Rinnegatamante/CHMM#31]
I get an error when opening a zip file.
**Error:[string "?"]:599: error opening file.**
I am using a cia install and I also used DSP Dump.
_Picture of the error log:_
![20170118_001427](https://cloud.githubusercontent.com/assets/6959837/22044271/1d465f40-dd14-11e6-9657-7ec6cadb3455.jpg)
_Picture of my /Themes folder_
![chmm_error](https://cloud.githubusercontent.com/assets/6959837/22044280/247fe510-dd14-11e6-8a4b-e640d626f9ed.PNG)

Thanks in advance.

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/CHMM2/issues/26
