### ISSUE TITLE
Crash on opening preview bgm.ogg

### ISSUE THREAD

**Issue by bakawun** [Rinnegatamante/CHMM#33]
Some theme previews will crash chmm2 after the loading bgm message.
Installing them works fine and so does previewing them withough bgm.

Here are 2 example themes that cause the crash
https://3dsthem.es/8897
https://3dsthem.es/7546

When it crashes i get the following on the bottom screen

Error:[string "?"]:1782: corrupt OG
G file.

Press A to restart
Press B to exit
Press Y to enable FTP server

FTP state: OFF

**Comment by Rinnegatamante** [comment]
That's not an issue with CHMM but an issue with the themes. They're probably using too big audio files as previews.

**Comment by bakawun** [comment]
What is the time and/or size limit for preview audio files for CHMM?

Also i respectfully disagree, CHMM should not crash on encountering large files, instead it should continue running but not play the preview if it is unable to do so.

**Comment by Rinnegatamante** [comment]
Depends on several info: Bitrate, Samplerate, Audiochannels.

Also i respectfully disagree, a theme before being released should be at least tested once by the creator. If so that issues would never happens. :)
