### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Poliwrath** [Rinnegatamante/CHMM#40]
it says error occured plz help rinnegatamante senpaii~~~~~

**Comment by ShinyNumber1** [comment]
Stop bugging him, go make some research yourself :v

**Comment by ShinyNumber1** [comment]
@Poliwrath hold the power button and try again.

**Comment by Poliwrath** [comment]
it say bootrom error wtf you hacked my ds lite

**Comment by Poliwrath** [comment]
noo senpai plzzzzzzzzzzzz help

**Comment by ShinyNumber1** [comment]
@Poliwrath  bootrom error=brick
duh

**Comment by Rinnegatamante** [comment]
Just a troll, don't care about him.
